name = "dingding-blog"
type = "javascript"

# Cloudflare Pages 配置
pages_build_output_dir = "public"

[site]
bucket = "./public"

[build]
command = ""
upload.format = "service-worker"

# KV命名空间配置
[[kv_namespaces]]
binding = "BLOG_POSTS"
id = "97c1ad6d710b42129dc204075412907e"

# 开发环境KV配置
[env.dev.kv_namespaces]
BLOG_POSTS = { binding = "BLOG_POSTS", id = "97c1ad6d710b42129dc204075412907e" } 