name = "dingding-blog"
type = "javascript"

[site]
bucket = "./public"

[build]
command = ""
upload.format = "service-worker"

# 开发环境KV配置示例
# 需要替换为实际的KV命名空间ID
[env.dev.kv_namespaces]
BLOG_POSTS = { binding = "BLOG_POSTS", id = "替换为你的KV命名空间ID" } 